### ISSUE TITLE
UC2550 & UC5550 Datasheet

### ISSUE THREAD

**Issue by Experiment-626** [ghi-electronics/Docs#104] opened 2018-02-02 20:58 UTC
It needs to be explained in the datasheet that BOOT0 and BOOT1/PB2 need to be pulled in the correct direction according to the Reference Manual under Boot configuration. It needs to also be noted that BOOT0 is inverted on our SoM so if you pull the pin low, it will be high and if you pull the pin high, it will be low.

**Comment by Arke64** [comment] 2018-09-19 17:28
Duplicate of #85

**Closed by Arke64** 2018-09-19 17:28 UTC
